name: Find Current Pull Request
author: Spear Educaiton
description: Find a PR associated with the current commit. Only if the current commit is the HEAD commit of an open PR.
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client.  Defaults to github provided token.
    default: ${{ github.token }}
  sha:
    description: Sha to get PR for.  Defaults to current sha.
    default: ${{ github.sha }}
outputs:
  pr:
    description: The PR if one was found. (e.g. '373')
  number:
    description: The PR's number if the PR was found (e.g. '373')
  title:
    description: The PR's title if the PR was found
  body:
    description: The PR's body if the PR was found
runs:
  using: node16
  main: 'main.js'
branding:
  icon: git-pull-request
  color: blue
